# Configuration for the HTTP endpoints.
name: "igi64"

web:
  http: foo.org:6666
  # Uncomment for HTTPS options.
  # https: 127.0.0.1:6664
  # tlsCert: /etc/email-services/tls.crt
  # tlsKey: /etc/email-services/tls.key