# Configuration for the HTTP(S) endpoints.
web:
  protocol: https
  host: foo.org
  port: 6664
  allowedOrigins:
    - 'https://foo.org:6664'
    - 'http://localhost:33143'
  tlsCert: certs/foo.org/cert.pem
  tlsKey: certs/foo.org/key.pem

database:
  type: sqlite3
  config:
    file: ../db/foo.db

#database:
#  type: postgres
#  config:
#    database: email
#    user: admin
#    password: admin

file:
  uploadApi: /api/file/upload
  folder: filerepo
